from tkinter import*
root=Tk()
root.geometry("444x333")
root.title("Address Entry Form")
def getdetails():
    print("The first name is :",firstvalue.get())
    print("The second name is :",secondvalue.get())
    print("The address line 1 is :",address1value.get())
    print("The address line 2 is :",address2value.get())
    print("The city is :",cityvalue.get())
    print("The state is :",statevalue.get())
    print("The postal code is :",postalvalue.get())
    print("The country  is :",countryvalue.get())
def deletedetails():
    first_entry.delete(0,END)
frame=Frame(root,relief=SUNKEN,borderwidth=4)
frame.grid()    
first_name=Label(root,text="First Name:").grid(row=0,column=1)
last_name=Label(root,text="Last Name:").grid(row=1,column=1)
address1=Label(root,text="Address Line 1:").grid(row=2,column=1)
address2=Label(root,text="Address Line 2:").grid(row=3,column=1)
city=Label(root,text="City:").grid(row=4,column=1)
state=Label(root,text="State/Province:").grid(row=5,column=1)
postal=Label(root,text="Postal Code:").grid(row=6,column=1)
country=Label(root,text="Country:").grid(row=7,column=1)
firstvalue=StringVar()
secondvalue=StringVar()
address1value=StringVar()
address2value=StringVar()
cityvalue=StringVar()
statevalue=StringVar()
postalvalue=StringVar()
countryvalue=StringVar()
first_entry=Entry(root,textvariable=firstvalue ,width=50).grid(row=0,column=2)
second_entry=Entry(root,textvariable=secondvalue ,width=50).grid(row=1,column=2)
address1_entry=Entry(root,textvariable=address1value ,width=50).grid(row=2,column=2)
address2_entry=Entry(root,textvariable=address2value ,width=50).grid(row=3,column=2)
city_entry=Entry(root,textvariable=cityvalue ,width=50).grid(row=4,column=2)
state_entry=Entry(root,textvariable=statevalue ,width=50).grid(row=5,column=2)
postal_entry=Entry(root,textvariable=postalvalue ,width=50).grid(row=6,column=2)
country_entry=Entry(root,textvariable=countryvalue ,width=50).grid(row=7,column=2)
frm_buttons=Frame().grid(ipadx=5,ipady=5)
submit=Button(frame,text="Submit",command=getdetails).grid(padx=10,ipadx=10,sticky="s",row=8,column=2)
clear=Button(frame,text="Clear",command=deletedetails).grid(ipadx=10,sticky="s",row=9,column=2)
root.mainloop()
